# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Filling Missing Dataset

In [2]:
from sklearn.impute import SimpleImputer

data = pd.read_csv('missingDataset.csv')

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

age = data.iloc[:,1:4].values

imputer = imputer.fit(age[:,1:4])
age[:,1:4] = imputer.transform(age[:,1:4])
age

array([[130.  ,  30.  ,  10.  ],
       [125.  ,  36.  ,  11.  ],
       [135.  ,  34.  ,  10.  ],
       [133.  ,  30.  ,   9.  ],
       [129.  ,  38.  ,  12.  ],
       [180.  ,  90.  ,  30.  ],
       [190.  ,  80.  ,  25.  ],
       [175.  ,  90.  ,  35.  ],
       [177.  ,  60.  ,  22.  ],
       [185.  , 105.  ,  33.  ],
       [165.  ,  55.  ,  27.  ],
       [155.  ,  50.  ,  44.  ],
       [160.  ,  58.  ,  28.45],
       [162.  ,  59.  ,  41.  ],
       [167.  ,  62.  ,  55.  ],
       [174.  ,  70.  ,  47.  ],
       [193.  ,  90.  ,  28.45],
       [187.  ,  80.  ,  27.  ],
       [183.  ,  88.  ,  28.  ],
       [159.  ,  40.  ,  29.  ],
       [164.  ,  66.  ,  32.  ],
       [166.  ,  56.  ,  42.  ]])

# Categorical Variable to Numeric Variable

In [3]:
country1 = data.iloc[:,0:1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

country1 = le.fit_transform(country1)
print(country1)

country2 = data.iloc[:,0:1].values
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

country2 = ohe.fit_transform(country2).toarray()
print(country2)

[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 0 0 0 0 0 0 0]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


C:\Users\HP\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Combining Columns

In [6]:
result = pd.DataFrame(data = country2, index = range(22), columns = ['fr', 'tr', 'us'])
print(result.T)
result2 = pd.DataFrame(data = age, index = range(22), columns = ['height', 'weight', 'age'])
print(result2.T)

gender = data.iloc[:,-1].values
gender = le.fit_transform(gender)
result3 = pd.DataFrame(data = gender, index = range(22), columns = ['gender'])
print(result3.T)

combinedData = pd.concat([result, result2, result3], axis = 1)
combinedData

s = pd.concat([result, result2], axis = 1)


     0    1    2    3    4    5    6    7    8    9   ...   12   13   14   15  \
fr  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  1.0   
tr  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  ...  0.0  0.0  0.0  0.0   
us  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  1.0  1.0  1.0  0.0   

     16   17   18   19   20   21  
fr  1.0  1.0  1.0  1.0  1.0  1.0  
tr  0.0  0.0  0.0  0.0  0.0  0.0  
us  0.0  0.0  0.0  0.0  0.0  0.0  

[3 rows x 22 columns]
           0      1      2      3      4      5      6      7      8      9   \
height  130.0  125.0  135.0  133.0  129.0  180.0  190.0  175.0  177.0  185.0   
weight   30.0   36.0   34.0   30.0   38.0   90.0   80.0   90.0   60.0  105.0   
age      10.0   11.0   10.0    9.0   12.0   30.0   25.0   35.0   22.0   33.0   

        ...      12     13     14     15      16     17     18     19     20  \
height  ...  160.00  162.0  167.0  174.0  193.00  187.0  183.0  159.0  164.0   
weight  ...   58.00   59.0   62

fr   tr   us  height  weight    age
0   0.0  1.0  0.0   130.0    30.0  10.00
1   0.0  1.0  0.0   125.0    36.0  11.00
2   0.0  1.0  0.0   135.0    34.0  10.00
3   0.0  1.0  0.0   133.0    30.0   9.00
4   0.0  1.0  0.0   129.0    38.0  12.00
5   0.0  1.0  0.0   180.0    90.0  30.00
6   0.0  1.0  0.0   190.0    80.0  25.00
7   0.0  1.0  0.0   175.0    90.0  35.00
8   0.0  1.0  0.0   177.0    60.0  22.00
9   0.0  0.0  1.0   185.0   105.0  33.00
10  0.0  0.0  1.0   165.0    55.0  27.00
11  0.0  0.0  1.0   155.0    50.0  44.00
12  0.0  0.0  1.0   160.0    58.0  28.45
13  0.0  0.0  1.0   162.0    59.0  41.00
14  0.0  0.0  1.0   167.0    62.0  55.00
15  1.0  0.0  0.0   174.0    70.0  47.00
16  1.0  0.0  0.0   193.0    90.0  28.45
17  1.0  0.0  0.0   187.0    80.0  27.00
18  1.0  0.0  0.0   183.0    88.0  28.00
19  1.0  0.0  0.0   159.0    40.0  29.00
20  1.0  0.0  0.0   164.0    66.0  32.00
21  1.0  0.0  0.0   166.0    56.0  42.00

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(s, combinedData, test_size=0.33, random_state=17)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


array([[-0.8660254 , -0.8660254 , -0.8660254 ,  1.15470054, -0.8660254 ,
        -0.8660254 , -0.8660254 ,  1.15470054, -0.8660254 ,  1.15470054,
        -0.8660254 ,  1.15470054,  1.15470054,  1.15470054],
       [ 1.34164079, -0.74535599,  1.34164079, -0.74535599, -0.74535599,
         1.34164079,  1.34164079, -0.74535599, -0.74535599, -0.74535599,
         1.34164079, -0.74535599, -0.74535599, -0.74535599],
       [-0.52223297,  1.91485422, -0.52223297, -0.52223297,  1.91485422,
        -0.52223297, -0.52223297, -0.52223297,  1.91485422, -0.52223297,
        -0.52223297, -0.52223297, -0.52223297, -0.52223297],
       [ 0.44440566, -0.17262038, -2.22937385, -0.22403922, -0.06978271,
         0.34156799, -2.02369851,  0.75291868, -0.32687689,  1.26710705,
         1.11285054, -0.12120154,  0.95859403,  0.29014915],
       [-0.37808452, -0.67215026, -1.78960006, -0.02520563, -0.26045822,
         1.3863099 , -1.67197376,  1.26868361, -0.43689767,  1.3863099 ,
         0.79817843, -0.61